# Generated by Django 6.0.3 on 2026-04-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0002_remove_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category_icons/', verbose_name='ロゴ画像'),
        ),
    ]
